# Keep the version in sync with pydantic-feedstock because the latest version can be incompatible.
{% set name = "pydantic-core" %}
{% set version = "2.39.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: b890a3990bd55ba5dab17fb6ae80eb25bb33e2f5b462da386562e7a168dd02de

build:
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  number: 0
  skip: true  # [py<39]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler("c") }}
    - {{ compiler("rust") }}
    - cargo-bundle-licenses
  host:
    - pip
    - python
    - maturin >=1.9,<2
  run:
    - python
    - typing-extensions >=4.14.1

test:
  imports:
    - pydantic_core
  commands:
    - pip check
    - python -c "from pydantic_core import PydanticUndefinedType"
  requires:
    - pip

about:
  home: https://github.com/pydantic/pydantic-core
  dev_url: https://github.com/pydantic/pydantic-core
  doc_url: https://docs.pydantic.dev
  summary: Core validation logic for pydantic written in rust
  description: |
    This package provides the core functionality for pydantic validation and serialization.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - xhochy
    - samuelcolvin
    - adriangb
    - dmontagu
    - pavelzw